# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: part2gRPC.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpart2gRPC.proto\x12\x0cStockTrading\"#\n\rLookupRequest\x12\x12\n\nstock_name\x18\x01 \x01(\t\"/\n\x0eLookupResponse\x12\r\n\x05price\x18\x01 \x01(\x02\x12\x0e\n\x06volume\x18\x02 \x01(\x05\"B\n\x0cTradeRequest\x12\x12\n\nstock_name\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\x0e\n\x06is_buy\x18\x03 \x01(\x08\"\x1f\n\rTradeResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"2\n\rUpdateRequest\x12\x12\n\nstock_name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\" \n\x0eUpdateResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\xe0\x01\n\x0cStockTrading\x12\x45\n\x06Lookup\x12\x1b.StockTrading.LookupRequest\x1a\x1c.StockTrading.LookupResponse\"\x00\x12\x42\n\x05Trade\x12\x1a.StockTrading.TradeRequest\x1a\x1b.StockTrading.TradeResponse\"\x00\x12\x45\n\x06Update\x12\x1b.StockTrading.UpdateRequest\x1a\x1c.StockTrading.UpdateResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'part2gRPC_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOOKUPREQUEST._serialized_start=33
  _LOOKUPREQUEST._serialized_end=68
  _LOOKUPRESPONSE._serialized_start=70
  _LOOKUPRESPONSE._serialized_end=117
  _TRADEREQUEST._serialized_start=119
  _TRADEREQUEST._serialized_end=185
  _TRADERESPONSE._serialized_start=187
  _TRADERESPONSE._serialized_end=218
  _UPDATEREQUEST._serialized_start=220
  _UPDATEREQUEST._serialized_end=270
  _UPDATERESPONSE._serialized_start=272
  _UPDATERESPONSE._serialized_end=304
  _STOCKTRADING._serialized_start=307
  _STOCKTRADING._serialized_end=531
# @@protoc_insertion_point(module_scope)
